services:

  backend:
    build:
      context: ./backend
    ports:
      - "8100:8000"
    environment:
      ENVIRONMENT: local
      LOG_LEVEL: INFO
      AWS_REGION: ${AWS_REGION:-ap-south-1}
      DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
      TERRAFORM_MODULES_PATH: /terraform-modules
    volumes:
      - ./backend/app:/app/app
      - ./terraform/modules:/terraform-modules:ro
    depends_on:
      - dynamodb-local

  frontend:
    build:
      context: ./frontend
    ports:
      - "3200:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8100
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8001:8000"
    command:
      - "-jar"
      - "DynamoDBLocal.jar"
      - "-inMemory"
      - "-sharedDb"